### ISSUE TITLE
Use the Projects and related classes in Occam directly.

### ISSUE THREAD

**Issue by ghost** [occam-proof-assistant/Open-CLI#6]
At the moment, much of the functionality is duplicated.

**Comment by ghost** [comment]
See https://github.com/occam-proof-assistant/Occam/issues/160.

**Comment by ghost** [comment]
This is related to https://github.com/occam-proof-assistant/Occam/issues/160.

**Comment by djalbat** [comment]
This is unlikely to happen now that they are also being used on openmathematics.org, too.
